// Given two strings s and t which consist of only lowercase letters.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Find the letter that was added in t.

// Input:
// s = "abcd"
// t = "abcde"

// Output:
// e
/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {

      var tempArrS = [],
          tempArrT = [];

      for (var i = 0, lenS = s.length; i < lenS; i++) {
        if (tempArrS[s[i]]) {
          tempArrS[s[i]]++;
        } else {
          tempArrS[s[i]] = 1;
        }
      }

      for (var j = 0, lenT = t.length; j < lenT; j++) {
        if (!tempArrS[t[j]]) {
          return t[j];
        }
        if (tempArrT[t[j]]) {
          tempArrT[t[j]]++;
        } else {
          tempArrT[t[j]] = 1;
        }
      }

      for (var k = 0; k < lenS; k++) {
        if (tempArrS[s[k]] !== tempArrT[s[k]]) {
          return s[k];
        }
      }

};
